{% set name = "scikit-data" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-data-{{ version }}.tar.gz
  sha256: d933e9822f7f8d1bb120ba313b64c45ea73e0d97c9b322797f3cfe42e3113428

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1004
  
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy >=1.12
    - scipy
    - scikit-learn
    - matplotlib-base
    - ipython
    - jupyter
    - ipywidgets
    - h5py
    - odo

test:
  imports:
    - skdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/OpenDataScienceLab/skdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The propose of this library is to allow the data analysis process more easy and automatic.'
  description: |
    This library offers functions to manipulate, clean and visualize data in a easy way.
  doc_url: http://skdata.readthedocs.io/
  dev_url: https://github.com/OpenDataScienceLab/skdata

extra:
  recipe-maintainers:
    - xmnlab
    - ocefpaf
