{% set name = "scikit-data" %}
{% set version = "0.1.3" %}
{% set sha256 = "697b9da63fbdc63dd85c9f1330f33171ea65ec5f77723b088c7df71b994d334b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py2k or py<35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - numpy >=1.12
    - scikit-learn
    - matplotlib
    - jupyter
    - ipywidgets
    - ipython
    - odo
    - scipy
    - h5py

test:
  imports:
    - skdata

about:
  home: http://github.com/OpenDataScienceLab/skdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The propose of this library is to allow the data analysis process more easy and automatic.'
  description: |
    This library offers functions to manipulate, clean and visualize data in a easy way.
  doc_url: http://skdata.readthedocs.io/
  dev_url: https://github.com/OpenDataScienceLab/skdata

extra:
  recipe-maintainers:
    - xmnlab
    - ocefpaf
