travis:
  secure:
    BINSTAR_TOKEN: lomom2JUKjfkP9+9aqAJ/ilqZj5SWuS8tCfRDOBrgXHZ8f1m0ONKJJHocfg8awC2YGhu5FCKl8SO1Vc5j+xnJC5mE6MbdXOieDqXlkrAHXXvrpM18wd0BWtJV+Wj/JbaXmwERk0PUxhHolGC4AcKxk0cjE1pckqu2Y5DHmGdRQPGn46cATm/tuklFvsUjhBlT0M/iPzxM7a1x0X6RqEl+/lmvj675WQluS5KJGJR6GENgOKPsnEbCbzatnFXk82kiJGajMErm+DQbpbT67eeFRGk/HCTJEzCLrzSRJvyCnPmqcKLTNm/48zH0AxchWm4u1CTmjGaj2wrmjDP4ucG1qC4pJBK4Z9OHfaW7YroqgRYoEjjAsw+lAIk6AoiqgIO/4KBTYyimgk1n5GsgcqK8Nc9Se2L9PSmenyQwEotuUW3UYATPETrhCeqPB9vM3e7AqM8E04fjDW2iywkV7NkE7AQmGLYEaXHp4nO1f0fV5ahKPHh5dL5mg6YC9XQV+AcryGq6u6cw3JnMjR0kpDbq9JhcJ/Apq/FTCSadan3uxDa9lOqMUrMmEhkumP3y2K3JsMKxbjMBD1ycQSLpZOnhDbeR9Co6okpWhI2XNS15dfD8yjj0WAfjPBf8I8gPa4G8+eWS2FkAnQ02Ii5PSYjiW/xMZshbBIp784lb217OHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
