appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UNQXRbniL1Ea8/7XrUFCcUqw3uBxBJeodca2YZzN7gUw9Vvkn08wewiv5O/yToomP47UsnYH7ddKsWV6hxFkuki/wsayhIinXgEX3a97yugZe6ZkwvuG1Fddd9x0dkbot+yQWRTNWeHTp8IxnSe7feBeVIjaX45Mi8ys/cGCi+VodTv5JIrZbw384khxrAlz9d/eb3zmRpJOPCX32NLrYS+xYGgWmZNVBGgIwfRr6TAQZlmJEK9DbDY1O/WPerZAVYEGX61Gl2NHpAAZs42875iUwfC4TI1z6V1WLYmLPHFxklBcvkKCJ5CjHfP2wBEOQpSOTYnb4Vf96hDLjNIECn46mdnig0503AWeADPjKB59uyQYl5uK143nLi71b3ZHNdTBJ5MruOtcCTP89EPa4s4qSk7UBw37OD0xGbX/DSzpVjkYx2F3V+6pJerYM2vCT/tphNz1t6uG1SkO3r4GwxbjQfPS5A08bt9dqGXJ3vqolykooHYCG9plKeBYU48y8XP5ThXxfLNjfe842hgV4DbC+zdUOmZ911eHWeumRF+E/sjtYb3/yAI6/N8zdp/eH05rXcG8txa9q+w0MC+kyaCvCSZMnWWnSS8XHujnuJ43Y0ntdyhBsk1+59U78P0yXyAgRlKk75NdoWieqlZxdy5hMrVTtBYR1+G81dcTTKY=}
